### ISSUE TITLE
Annotated dynamic import causes crash

### ISSUE THREAD

**Issue by thovden** [pahen/madge#211] opened 2019-05-14 13:33 UTC
When using webpack annotations for dynamic imports, madge tries to make sense of the first argument to the import, which will be `undefined`. 

So: 
```javascript
const Graph =  React.lazy(() => import(/* webpackChunkName: 'react-graph-vis' */ `react-graph-vis`))
```

causes

```bash
✖ TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:2025:20)
    at mangleScopedPackageName (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27283:16)
    at mangleScopedPackageNameWithTrace (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27270:23)
    at loadModuleFromImmediateNodeModulesDirectory (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27195:83)
    at /Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27172:39
    at Object.forEachAncestorDirectory (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:12577:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27166:19)
    at loadModuleFromNearestNodeModulesDirectoryTypesScope (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27162:16)
    at tryResolve (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27348:28)
    at classicNameResolver (/Users/torgeir/dev/signatu/signatu/node_modules/typescript/lib/typescript.js:27324:24)

```

**Comment by Zjaaspoer** [comment] 2019-06-14 14:47
Getting the same issue, typescripts `import(...)` gives the above mentioned error

**Comment by jfschwarz** [comment] 2020-04-03 14:00
Did anyone find a workaround for this yet?

**Comment by tonivj5** [comment] 2020-06-19 16:50
Maybe related to https://github.com/pahen/madge/issues/157?

**Comment by raheelriax** [comment] 2020-07-16 14:22
I am also facing this issue...

**Comment by bradennapier** [comment] 2020-07-24 21:20
Running into this as well - don't use dynamic import that I know of - but might use dynamic type imports somewhere?

```
➜  git:(P9-1620-feature/more-expand-error-coverage) ✗ npx madge --image graph.svg --extensions ts,tsx --ts-config ./tsconfig.json -c  ./src/services/rest-api

✖ TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/Users/Shared/abc//node_modules/typescript/lib/typescript.js:2060:20)
```

**Comment by devinrhode2** [comment] 2020-10-06 01:57
"typescript" and "lastIndexOf" would be nice keywords to add to the issue title here

Also seems like this issue is a duplicate of #157

And there's no good solution (https://github.com/pahen/madge/issues/157#issuecomment-390969446)
> Thanks for reporting the issue. I'm afraid that the fancy footwork is defeating static analysis here :) The only way for dependency-tree to recognize those imports is to evaluate the code to inline the assignments. Maybe facebook's prepack could be a good prepass filter for dependency-tree; not sure if anyone has tried that.

**Comment by devinrhode2** [comment] 2020-10-06 02:34
Just change all the dynamic `import(` calls to be static import statements at the top, run madge, git stash the conversion of `import(` calls (or put it on a branch).

**Comment by villelaitila** [comment] 2020-10-28 23:31
Replacing the malfunctioning code place might be much simpler instead of changing the code under analysis.

If making the function mangleScopedPackageName(packageName) return "undefined" whenever packageName is undefined, the madge doesn't crash but just ignores that part of the code. (I am not fully aware of all the consequences)

Hackish way to do it after madge has been installed so that node_modules is located under /usr/lib:

``bash
sed -i  "s/if (ts.startsWith(packageName/if (typeof(packageName) === \"undefined\") return \"undefined\"; if (ts.startsWith(packageName/g" /usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js
``

![Screenshot from 2020-10-29 01-27-42](https://user-images.githubusercontent.com/5195944/97507587-26ab3a80-1986-11eb-8521-75b1897d6a30.png)

**Comment by devinrhode2** [comment] 2020-10-29 01:08
Maybe the best approach is: don't crash, but instead just emit a warning.
Crashing is definitely not a very useful behavior due to this issue

**Comment by pahen** [comment] 2020-10-29 07:10
This should be reported and fixed in the Typescript project instead of finding workarounds in Madge.

**Comment by villelaitila** [comment] 2020-10-29 10:14
@pahen  What do you think will it be probable that they actually accept that sort of pull request related to the function mangleScopedPackageName or is it more probable to find out a way from madge repository to fix it? I'll report it anyway there.

**Comment by pahen** [comment] 2020-10-30 11:05
I don't know @villelaitila But it's worth trying. If they refuse to fix it we can start working on some sort of workaround in Madge.

**Comment by villelaitila** [comment] 2021-01-29 15:31
It seems we will need to add more info to https://github.com/microsoft/TypeScript/issues/41332

**Comment by villelaitila** [comment] 2021-02-16 22:22
I cannot reproduce this anymore with madge 4.0.0 that has typescript version 3.9.9.

**Comment by pahen** [comment] 2021-02-17 08:21
> I cannot reproduce this anymore with madge 4.0.0 that has typescript version 3.9.9.

Sweet! I'm closing this for now then.

**Closed by pahen** 2021-02-17 08:21 UTC
