### ISSUE TITLE
Yarn workspaces

### ISSUE THREAD

**Issue by NathanHazout** [pahen/madge#290] opened 2021-07-28 12:02 UTC
I have a yarn workspaces, with 100 packages dependent on each other (using `@my-company/package-name` syntax).  
Can this tool help me find circular dependencies? It doesn't seem to pick up my internal packages...

**Comment by pahen** [comment] 2021-07-29 09:28
Duplicate of https://github.com/pahen/madge/issues/253. Sorry, no support for Yarn workspaces.

**Closed by pahen** 2021-07-29 09:28 UTC
