### ISSUE TITLE
Hangs on windows when generating an image

### ISSUE THREAD

**Issue by damiangreen** [pahen/madge#324] opened 2022-09-15 10:54 UTC
On our app of 2000+ components .

It apparently just hangs when attempting to generate the image
(Windows)

```  madge --extensions ts,tsx src/ -i img.png
Processed 4200 files (15.1s) (268 warnings)
```

**Comment by SebTVisage** [comment] 2023-01-30 15:05
Same issue on mac using the CLI. I run it on the `dist` folder of a node project using JS & TS to avoid any issue related to TS.

Tried with v5 instead v6 (`npm i -g madge@^5`), it worked.

**Comment by PabloLION** [comment] 2023-01-30 19:25
Seems this is a performance issue. Since we are not planning to work on it recently, this work around can be very helpful. Thanks!

**Comment by epreston** [comment] 2023-02-05 03:40
Graphs silently fail since upgrading to 6.  Downgrading to 5 sorted things out.

**Comment by kamiazya** [comment] 2023-02-05 13:03
There was an issue with the ts-graphviz package.

It has been fixed in [v1.5.3](https://github.com/ts-graphviz/ts-graphviz/releases/tag/v1.5.3), so reinstalling madge@6 should not reproduce this issue.

Please let me know if you reproduce this issue again, as I will close this issue once it is closed.

**Closed by kamiazya** 2023-02-05 13:03 UTC
Labels: bug, viz, cli

**Comment by epreston** [comment] 2023-02-05 14:48
Working well.  Thank you.
